Virtual product:
    virtual_product_path: configs/dea_virtual_product_landsat.yaml
    virtual_product_name: ls_nbart_ndwi
Input files:
    grid_path: data/raw/50km_albers_grid_clipped.geojson
    points_path: data/raw/tide_points_coastal.geojson
    modifications_path: data/raw/estuary_mask_modifications.geojson
    geomorphology_path: data/raw/Smartline.gpkg
    region_attributes_path: data/raw/Primary_compartments.geojson