
---
name: Tests

on:
  pull_request:
    branches:
        - 'develop'
        - 'tests_validation'
    paths:
      - '**'
      - '.github/workflows/test.yml'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'

  push:
    branches:
      - 'develop'
      - 'tests_validation'
    paths:
      - '**'
      - '.github/workflows/test.yml'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0          

      - name: Dockerized Integration test
        run: |
          mkdir artifacts
          chmod a+rw artifacts
          wget --no-verbose https://www.dropbox.com/s/vj2rqkwy9al144w/tide_models.zip?dl=1 -O tide_models.zip
          unzip -q tide_models.zip

          docker-compose up -d
          docker-compose exec -T coastline /bin/sh -c "sh ./docker/coastline/wait-for-db; pytest --cov=coastlines --cov-report=xml tests/"
          docker-compose exec -T coastline /bin/sh -c "cp coverage.xml /mnt/artifacts"
          docker-compose exec -T coastline /bin/sh -c "cp data/processed/tests/coastlines_tests.gpkg /mnt/artifacts/coastlines_tests.gpkg"
          docker-compose exec -T coastline /bin/sh -c "cp data/validation/processed/stats_tests.png /mnt/artifacts/integration_test_results.png"
          docker-compose exec -T coastline /bin/sh -c "cp tests/README.md /mnt/artifacts/README.md"
          docker-compose down

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1

      - name: Commit integration results
        run: |
          cp ./artifacts/integration_test_results.png ./tests/integration_test_results.png
          cp ./artifacts/README.md ./tests/README.md
          git status
#          git commit -am 'Automatically update integration test validation results'
#          git push

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically update integration test validation results

      - uses: actions/upload-artifact@v3
        with:
          name: output_geopackage
          path: ./artifacts/coastlines_tests.gpkg

      - uses: actions/upload-artifact@v3
        with:
          name: png
          path: ./artifacts/stats_tests.png

      - uses: actions/upload-artifact@v3
        with:
          name: readme
          path: ./artifacts/README.md

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./artifacts/
          fail_ci_if_error: false

