
---
name: Tests

on:
  pull_request:
    branches:
        - 'develop'
        - 'tests_validation'
    paths:
      - '**'
      - '.github/workflows/test.yml'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'

  push:
    branches:
      - 'develop'
      - 'tests_validation'
    paths:
      - '**'
      - '.github/workflows/test.yml'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dockerized Integration test
        run: |
          mkdir artifacts
          chmod a+rw artifacts
          wget https://www.dropbox.com/s/vj2rqkwy9al144w/tide_models.zip?dl=1 -O tide_models.zip
          unzip tide_models.zip

#          docker-compose up -d
#          docker-compose exec -T coastline /bin/sh -c "sh ./docker/coastline/wait-for-db; pytest --cov=coastlines --cov-report=xml tests/"
#          docker-compose exec -T coastline /bin/sh -c "cp coverage.xml /mnt/artifacts"
#          docker-compose down

      - run: ls
      
      - run: ls artifacts
      
      - run: ls data
      
      - run: ls data/processed
      
      - run: ls data/processed/testing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./artifacts/
          fail_ci_if_error: false
          
      - uses: actions/upload-artifact@v3
        with:
          name: output_geopackage1
          path: data/processed/testing/coastlines_testing.gpkg

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: output_geopackage2
          path: ./artifacts/data/processed/testing/coastlines_testing.gpkg

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: output_geopackage3
          path: ./data/processed/testing/coastlines_testing.gpkg
